### ISSUE TITLE
generate mapping for one to many entites

### ISSUE THREAD

**Issue by masoodinfo** [alirezanet/Gridify#10]
hi 
I have query like below :
var mp=new GridifyMapper<student>().GenerateMappings().AddMap("coursename",x=>x.course.where(y=>y.name==@name).count()>0)

i use LinqKit perdicate for this query but i must declare it for all operator (==.contains,not con.....)

how can run by Gridify?

**Comment by alirezanet** [comment]
Your query is wrong, you need to start from your collection (course) and manually map parent class properties. in the above example, you're doing it in reverse order. 
also, gridify just converting your string to the actual expression, you should at least provide a Linq example of what you need to achieve.

**Comment by masoodinfo** [comment]
from st in db.students
where st.courses.where(x=>x.name=="abcd").count()>0
select st

I am on students page ,that has a data grid.
user want filter students grid by it condition

**Comment by alirezanet** [comment]
exactly, if you have a two-way relation between students and courses you can simply switch your collections. 
e.g: 
``` c#
var query = from course in db.courses
where course.Name == "abcd"
select course.Student
```
this way you can use gridify without problem because your query is normalized now. this query does exactly what you want.
and this way because your student relation is not a collection you can Add your mappings for the student entity.

**Comment by masoodinfo** [comment]
Ok.
How do you do  If i want add other conditiones related with student in one query ?
Tnx a lot

**Comment by alirezanet** [comment]
e.g
``` c#
var gq = new GridifyQuery() { Filter = "Age<30 , StudentName^a ,  CourseName==abcd" , SortBy = "StudentName" };
var gm = new GridifyMapper<Course>()
                    .AddMap("CourseName", x=> x.Name)
                    .AddMap("StudentName", x=> x.Student.Name)
                    .AddMap("Age" , x=>  x.Student.Age);

var query = db.Courses.ApplyEverything( gq );
var result = query.Select(x=> x.Student).ToList(); // you can select anything here
```

**Comment by alirezanet** [comment]
Yes, it depends on what you want exactly there are few ways to write a single query. in this case, your main query was on `CourseName` so it makes sense to select students related to the courses.
 usually, if you want to select **all students** you shouldn't use filtering on courses.
these tricks help you implement 99 percent of scenarios, but I agree there are some edge cases you can't do much. (I never faced one yet).

**Comment by masoodinfo** [comment]
tnx a lot for replay

**Comment by alirezanet** [comment]
Your requested feature is available in the `v2`.
