### ISSUE TITLE
Filter on nested collections of collections

### ISSUE THREAD

**Issue by cirrusone** [alirezanet/Gridify#13]
Thanks for an excellent library.

I've read through the code and couldn't see any examples of filtering from the base collection where there are nested collections inside collections.

Eg is something like this possible without isolating each collection, `Filter = "Level2List_Level3List_Property1 >= 3.0"`?

I would still want to return items of type `Level1` but filter on properties of `Level3`.
```

using Gridify;
using System.Collections.Generic;
using System.Linq;

namespace GridifyNestedProperties
{
    class Program
    {
        static void Main(string[] args)
        {
            Level1 level1 = new Level1()
            {
                Id = 1,
                Name = "Level1Name",
                Level2List = new List<Level2>()
                {
                    new Level2() { Id = 101, Name = "Level2_1", Level3List = new List<Level3>() { new Level3() { Property1 = 2.0, Property2 = 100.0, Level = 0 } } },
                    new Level2() { Id = 102, Name = "Level2_2", Level3List = new List<Level3>() { new Level3() { Property1 = 3.0, Property2 = 200.0, Level = 0 } } },
                    new Level2() { Id = 103, Name = "Level2_3", Level3List = new List<Level3>() { new Level3() { Property1 = 4.0, Property2 = 300.0, Level = 0 } } }
                }
            };

            Level1[] array = new Level1[1];
            array[0] = level1;
            var ds = array.AsQueryable();

            // Multi Nested Property
            var gq2 = new GridifyQuery { Filter = "Level2List_Level3List_Property1 >= 3.0" };
            var gm2 = new GridifyMapper<Level1>()
               .GenerateMappings()
               .AddMap("Level2List_Level3List_Property1", q => q.Level2List.SelectMany(x => x.Level3List.SelectMany(y => y.Property1)));

            var actual2 = ds.AsQueryable()
               .ApplyFiltering(gq2, gm2)
               .ToList();

        }
    }

    public class Level1
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Level2> Level2List { get; set; }
    }

    public class Level2
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Level3> Level3List { get; set; }
    }

    public class Level3
    {
        public int Level { get; set; }
        public double Property1 { get; set; }
        public double Property2 { get; set; }
    }
}
```

**Comment by alirezanet** [comment]
> I would still want to return items of type Level1 but filter on properties of Level3.
Hi, In your example filtering on the nested collections doesn't make sense because you have only **one** Level1 item in your collection (ds) so you can not filter anything here. but I am trying to add a feature to support these kinds of scenarios that you have multiple Level1 items in your initial DS.

I'm planning to release this feature in the next version2 alpha version.

**Comment by cirrusone** [comment]
My example only added a single Level1 item but I can see scenarios where I might want to filter a base single object with nested collections and also a base collection with nested collections.

Thanks for looking into this as it will make it an even more powerful library.

Another thing I thought about which may improve performance would it be possible to add options to pre-compile the filter expressions eg [Expression<TDelegate>.Compile Method](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression-1.compile?view=net-5.0)

**Comment by alirezanet** [comment]
> My example only added a single Level1 item but I can see scenarios where I might want to filter a base single object with nested collections and also a base collection with nested collections.
Thanks for looking into this as it will make it an even more powerful library.

Yes, you are right. your welcome. 

> Another thing I thought about which may improve performance would it be possible to add options to pre-compile the filter expressions eg Expression.Compile Method

I think we should discuss this in another issue because gridify usually been used alongside an ORM like EF so gridify doesn't even use the expression and compiled expressions can not be used in the EF but in other cases (without any ORMs) maybe this feature can be usufull.

**Comment by alirezanet** [comment]
This feature is available in `2.0.0-beta.1`. 
It would be awesome if you can give me your feedback about this.

usage:
```c#
 var gm = new GridifyMapper<Level1>()
            .GenerateMappings()
            .AddMap("prop1", l1 => l1.Level2List.SelectMany(l2 => l2.Level3List).Select(l3 => l3.Property1));
```

**Comment by cirrusone** [comment]
Thanks for such a fast update. For simple logic this works brilliantly.

After testing I do have a few scenarios where this could be improved further but not sure how complex this is?
Say I wanted to filter to find where BOTH `Level2List_Id=101` and that same item has `Level2List_Level3List_Property1>=3.0`
the filter `Filter = "Level2List_Id=101, Level2List_Level3List_Property1>=3.0"` doesn't work as the AND is finding two separate instances of Level2.

Is there a way to introduce chained logic so that there can be sub filters? 

Eg something like `Filter = "Level2List_Id=101 => Level3List_Property1>=3.0"`

Ie are there any records with Level2.Id==101 and that same item also has Level3List_Property1>=3.0?

The example below returns 1 item as both conditions are met but in the above example it should return zero items as there is no data with Level2.Id == 101 and also the Level3 Property1 >= 3.0.


```
        static void Main(string[] args)
        {
            Level1 level1 = new Level1()
            {
                Id = 1,
                Name = "Level1Name",
                Level2List = new List<Level2>()
                {
                    new Level2() { Id = 101, Name = "Level2_1", Level3List = new List<Level3>() { new Level3() { Property1 = 2.0, Property2 = 100.0, Level = 0 } } },
                    new Level2() { Id = 102, Name = "Level2_2", Level3List = new List<Level3>() { new Level3() { Property1 = 3.0, Property2 = 200.0, Level = 1 } } },
                    new Level2() { Id = 103, Name = "Level2_3", Level3List = new List<Level3>() { new Level3() { Property1 = 4.0, Property2 = 300.0, Level = 2 } } }
                }
            };

            Level1[] array = new Level1[1];
            array[0] = level1;
            var ds = array.AsQueryable();

            // Multi Nested Property
            var gq2 = new GridifyQuery { Filter = "Level2List_Id=101, Level2List_Level3List_Property1>=3.0" };
            var gm2 = new GridifyMapper<Level1>()
            .GenerateMappings()
            .AddMap("Level2List_Level3List_Property1", l1 => l1.Level2List.SelectMany(l2 => l2.Level3List).Select(l3 => l3.Property1))
            .AddMap("Level2List_Id", l1 => l1.Level2List.Select(l3 => l3.Id));

            var actual2 = ds.AsQueryable()
               .ApplyFiltering(gq2, gm2)
               .ToList();
        }
```

**Comment by alirezanet** [comment]
hmm, Interesting you are absolutely right. I'm thinking about using parenthesis to separate chain filtering from normal filtering.  something like `(Level2List_Id=101, Level2List_Level3List_Property1>=3.0) , Id < 10`. 
I'll look into this for the next beta version. probably `2.0.0-beta-3`
