### ISSUE TITLE
DateTime Kind and PostgreSQL

### ISSUE THREAD

**Issue by BigMakCode** [alirezanet/Gridify#134]
### Version

2.12.0

### Details

1. When I send an http request with datetime filter in format 2023-11-14T14:36:15.615Z, Gridify parses this value into the Unspecified Kind format. To work with PostgresSQL.EFCore, I need use the UTC Kind format.
2. Let's say I wrote my own gridify mapper and am parsing values into the kind format I need (UTC). But if in the database model the datetime property is a nullable datetime, then it is converted in [BaseQueryBuilder.cs](https://github.com/alirezanet/Gridify/blob/master/src/Gridify/QueryBuilders/BaseQueryBuilder.cs) into an unspecified datetime type. Because GetType from an [object returns a nested type](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/ms366789(v=vs.90)), and the type inside the expression is the property type from the database model. This is a big problem. I suggest adding custom processing on [line 173](https://github.com/alirezanet/Gridify/blob/a90ea4199100299164f34ac71ae49610509f2423/src/Gridify/QueryBuilders/BaseQueryBuilder.cs#L173) for Nullable\<DateTime> properties.

### Steps to reproduce

- Add PostgreSQL Database Context
- Create nullable DateTime property in database model
- Send Gridify query with DateTime format Kind = UTC
- LINQ query will be generated with another DateTime Kind

**Comment by alirezanet** [comment]
I don't believe your problem is particularly related to PostgreSQL or Nullable types. This behavior is consistent with regular expressions as well. However, without an example, I might be mistaken—if so, please let me know.

It appears you're using the DateTime class in your model. In this scenario, you need to convert the values manually because DateTime does not inherently support time zones. For instance, if you have a model with a NormalDateTime property like this:

```csharp
class TestModel
{
	public DateTime? NormalDateTime { get; set; }
	public DateTimeOffset? DateTimeOffset { get; set; }
}
```

The generated expression for DateTime differs from DateTimeOffset because DateTime does not account for the time zone:

``` csharp
var dateTimeString = "2023-11-14T14:36:15.615Z";

new QueryBuilder<TestModel>()
	.AddCondition($"NormalDateTime={dateTimeString}")
	.BuildFilteringExpression()
	.ToString()
	.Dump(); 
// NormalDateTime expression:  __TestModel => (__TestModel.NormalDateTime == 14/11/2023 15:36:15)

new QueryBuilder<TestModel>()
	.AddCondition($"DateTimeOffset={dateTimeString}")
	.BuildFilteringExpression()
	.ToString()
	.Dump(); 
// DateTimeOffset expression: __TestModel => (__TestModel.DateTimeOffset == 14/11/2023 14:36:15 +00:00)
```
When DateTime is parsed from a string, it typically results in DateTimeKind.Unspecified unless explicitly set otherwise. If you're dealing with UTC dates, could updating your model to use DateTimeOffset be a solution?

**Comment by BigMakCode** [comment]
@alirezanet Thank you for your response!
I changed the types in my models to DateTimeOffset and that really helped. I no longer get the error "Cannot write DateTime with Kind=Unspecified to PostgreSQL type 'timestamp with time zone',".
Now I will try to understand in my free time what needs to be used in the EFCore+NpgSql models - DateTime or DateTimeOffset. I always used the regular DateTime and didn’t think about DateTimeOffset.
But I want you to know that when the database model has the `DateTime?` property, then on line 180 in [this](https://github.com/alirezanet/Gridify/blob/a90ea4199100299164f34ac71ae49610509f2423/src/Gridify/QueryBuilders/BaseQueryBuilder.cs#L180) file a type conversion occurs, in which the Kind indication is lost (Conversion from `DateTime`(parsed value from HTTP request) to `DateTime?` (because DB model is nullable DateTime) leads to `DateTimeKind.Unspecified`). Now I'm not sure if this is a problem because I think I've been using DateTime incorrectly in EFCore and Postgres my whole life.
Thanks for your help, your library is incredibly cool. I think that this issue can be closed.

**Comment by BigMakCode** [comment]
It seems quite difficult to pass "plus" through the query parameter

![image](https://github.com/alirezanet/Gridify/assets/81349914/f79ef871-bd98-4624-a5a8-683a37febf53)

**Comment by BigMakCode** [comment]
So, DateTimeOffset didn't work for me, so I got out of the problem like this:
```CSharp
// type fixer, line 166, file BaseQueryBuilder.cs
if (value is not null && (body.Type != value.GetType() && Nullable.GetUnderlyingType(body.Type) != value.GetType()))
```
([file](https://github.com/alirezanet/Gridify/blob/a90ea4199100299164f34ac71ae49610509f2423/src/Gridify/QueryBuilders/BaseQueryBuilder.cs#L166))

I have a custom mapping to parse and convert the datetime filter values to `DateTimeKind.Utc`:
```CSharp
private static IGridifyMapper<TItem> AddDatetimeMappings<TItem>(this IGridifyMapper<TItem> mappings)
{
    Type itemType = typeof(TItem);
    var props = itemType.GetProperties(BindingFlags.Public | BindingFlags.Instance)
        .Where(x => x.PropertyType == typeof(DateTime) || x.PropertyType == typeof(DateTime?));
    foreach (var property in props)
    {
        mappings.AddMap(property.Name, p => DateTimeHelpers.ParseDateTime(p));
    }
    return mappings;
}
```

But on the line [166](https://github.com/alirezanet/Gridify/blob/a90ea4199100299164f34ac71ae49610509f2423/src/Gridify/QueryBuilders/BaseQueryBuilder.cs#L166), Gridify code converts `DateTime` to `DateTime?` and unfortunately, this is standard unpleasant behavior of .NET, which resets Kind to Unspecified upon conversion.
In this case, I skip the conversion from type T to type Nullable\<T>. I don’t know if you need such a correction, but I’ll keep this edit in my code, it helped me.

**Comment by BigMakCode** [comment]
@alirezanet Thank you for your response

Code sample:
```CSharp
// Source string
string dateTimeStringUtc = "2023-11-14T14:36:15.615Z";

// Like your mapping solution 'mappings.AddMap("dt", q => q.NormalDateTime, value => DateTime.Parse(value, null, DateTimeStyles.AdjustToUniversal))'
DateTime dt1 = DateTime.Parse(dateTimeStringUtc, null, DateTimeStyles.AdjustToUniversal);
Console.WriteLine("Parsed value: {0}, DateTimeKind: {1}", dt1.ToString("O"), dt1.Kind);

// It is the same action such as in https://github.com/alirezanet/Gridify/blob/a90ea4199100299164f34ac71ae49610509f2423/src/Gridify/QueryBuilders/BaseQueryBuilder.cs#L180
var converter = TypeDescriptor.GetConverter(dt1.GetType());
DateTime converted = (DateTime)converter.ConvertFromString(dateTimeStringUtc.ToString())!;
Console.WriteLine("Converted value: {0}, DateTimeKind: {1}", converted.ToString("O"), converted.Kind);
```

Output:
```Bash
Parsed value: 2023-11-14T14:36:15.6150000Z, DateTimeKind: Utc
Converted value: 2023-11-14T08:36:15.6150000-06:00, DateTimeKind: Local
```

You can see that DateTimeKind.Utc was lost after convertation - it was UTC before

**Comment by alirezanet** [comment]
Hi @BigMakCode, 
Thank you for the feedback, you were right. this issue led to a huge improvement to the type fixer in Gridify, from the next version if the types are the same (when we use a mapper convertor) we can safely skip the type fixer.
Soon, I'll release a new version including this fix.

**Comment by alirezanet** [comment]
Please try version `v2.13.0`, I believe this release can solve the issue

**Comment by BigMakCode** [comment]
@alirezanet Hello! It works:
![image](https://github.com/alirezanet/Gridify/assets/81349914/28560562-dd88-42d3-9477-eb8e6d1dab78)
Thank you very much for this fix! 🎉 You are the best 😊
