### ISSUE TITLE
Support for. NET8

### ISSUE THREAD

**Issue by samchenws** [alirezanet/Gridify#138]
### Details

Please Support for. NET8
![1699982277168](https://github.com/alirezanet/Gridify/assets/37535153/7f497f25-322d-4864-9df9-4ff61c2b89a3)
thank

**Comment by alirezanet** [comment]
Hi @samchenws,
I'm planning to drop net5 support and add net8.0 in a few days. wait for the next minor version.

**Comment by mo3in** [comment]
hi @alirezanet,
Gridify currently work as well in .net 8. just need to update EF dependency version ...

**Comment by agriffard** [comment]
Thank you. Can we expect a new Nuget package version soon?

**Comment by alirezanet** [comment]
Hi @agriffard,
I'll release a new version tomorrow.
