### ISSUE TITLE
Cleanup dependencies

### ISSUE THREAD

**Issue by thompson-tomo** [alirezanet/Gridify#161]
### Details

System.Reflection.Emit is provide as part of the framework & as such an explicit dependency is not needed especially on the newer TFM.

**Comment by alirezanet** [comment]
Hi @thompson-tomo,
I didn't check dotnet 8, but I remember we needed this package in the previous versions. I'll check later but feel free to send a PR if you want to remove it for dotnet 8

**Comment by thompson-tomo** [comment]
All done as #162
