### ISSUE TITLE
Passing filter value on CustomOperator Expression creation - for ContainsAny operator

### ISSUE THREAD

**Issue by Kuchasz** [alirezanet/Gridify#167]
There is one thing in that **awesome library** that i struggle with as much i can't overcome on my own.

### The problem

 What i try to achieve is a filter that allows finding rows containing any of values i look for. Look at the example below:

```csharp 

//the model i want to filter out
class Artist {
    public string[] FavouriteColors { get; set; }
}

//my custom operator (already registered)
class ContainsAnyOperator : IGridifyOperator
{
    public string GetOperator()
    {
        return "#ContainsAny";
    }

    public Expression<OperatorParameter> OperatorHandler()
    {
        return (prop, value) => ((string[])prop).Any(p => ((string[])value).Contains(p));
    }
}

//somewhere in my data fetching level
var mapper = new GridifyMapper<Artist>()
    .GenerateMappings()
    .AddMap(nameof(Artist.FavouriteColors), h => h.FavouriteColors, value => value.Split(";", StringSplitOptions.RemoveEmptyEntries).ToArray());

var result = query.GridifyQueryable(queryModel.ToGridifyQuery(), mapper);

//filter expression sent from the client side
//favouriteColors #ContainsAny red;green;blue

```

EFCore can't handle such expressions properly. It just throws an exceptions that such expressions may not be translated into sql queries. 

### Proposed solution
A workaround may be combining multiple .Contains statements into single Expression with Or operator. I'd like to achieve that at custom operator level but it seems to be impossible. Custom operators API gives no information about the filter value during Expression instance creation. Maybe passing the filter value (OperatorParameter.value) as parameter to OperatorHandler function would allow me to create such aggregated expression? I'd just turn every collection item into Expression like `prop.Contains(item)` and then Aggregate them with Expression.OrElse. Value used in filters is known ahead of SQL query execution, passing it to the Expression "builder" function should be possible (i hope).

### The bad workaround
That issue may be also overcomed by creation of IN style operator you described few months ago https://github.com/alirezanet/Gridify/issues/135 and combining multiple its statements at the client side but it looks like overuse of APIs provided by the library:
```
(favouriteColors #In red|favouriteColors #In green|favouriteColors #In blue)
```

**Comment by alirezanet** [comment]
Hi @Kuchasz,
Actually, you might not need any additional operator for this, Gridify by default supports nested collection if I understand the problem correctly.
Can you explain what you want to achieve exactly? or maybe share a LINQ version of your desired query.

**Comment by alirezanet** [comment]
Hi @Kuchasz,
I wouldn't recommend using a Custom operator in this case unless you want to use the EF.Functions, 
look at this example and let me know if it works for you:

```csharp

var dataSource = new List<Artist>() { new() {FavouriteColors = ["Green", "Blue"]}}.AsQueryable();

var mapper = new GridifyMapper<Artist>()
		.AddMap("fc", w=> w.FavouriteColors.Select(fc => fc));


var query = dataSource.ApplyFiltering("fc=Red|fc=Blue|fc=Yellow", mapper);

var lst = query.ToList().Dump();

class Artist
{
	public string[] FavouriteColors { get; set; }
}
```

**Comment by Kuchasz** [comment]
Your snippet of code works well but with IQueryable datasource tied to in-memory collection. It does not work with IQueryable coming from EFCore DBContext. The exception i get is the same exception like that one in case of CustomOperator trying to do both .Any and .Contains at the same time: 
```
...query... could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
```

It would be perfect to define single filter statement with multiple values in it. instead of defining multiple filter statements with single value each `"fc #Operator Red,Blue"` vs `fc=Red|fc=Blue`. I was able to achieve first query working but only with fc being single value not collection of values.


NOTE: Im using EFCore 7.x, i've seen some articles about primitives collections search improvements in EFCore 8. Maybe such queries work well on newer version.

**Comment by alirezanet** [comment]
Since Gridify is just converting string queries to LINQ, it would be nice if you share your desired LINQ version of what you expect, so we can compare Gridify results with it and see why EntityFramework is complaining ... 
for example, some expressions no matter generated by Gridify or it is native LINQ are not supported by EntityFramework and we can't do anything about that.

**Comment by Kuchasz** [comment]
LINQ queries to EFCore will have exactly the same issues. I assume the same mechanisms are used underneath by Gridify. It is possible to build LINQ Expression the way that it could be handled by EFCore. The only solution for now is generation of multiple where in statements combined with OR. I want Gridify to do that for me when i specify 'ContainsAny' operator. I dont want the need to specify the filters this way: `fc=Red|fc=Blue|fc=Green|fc=Foo` everywhere, client side multiselect components don't work this way. I'd like to define that filter this way: `fc #In Red;Blue;Green;Foo`.

Gridify's custom operator mechanisms let the users build their own LINQ expressions. Filter's value (array of desired values) is not passed to method that builds the Expression but to expression body. With values known one level higher it should possible to build operator i need. Treat below code as a pseudocode, its something generated by chatgpt. It creates below expression dynamically.
```csharp
query.Where(a =>a.FavouriteColors.Contains("Red") 
    || a.FavouriteColors.Contains("Blue") 
    || a.FavouriteColors.Contains("Green") 
    || a.FavouriteColors.Contains("Foo"));
``` 


```csharp
    public Expression<OperatorParameter> OperatorHandler(string[] values)
    {
        // Parameters for the input arrays
        var paramProp = Expression.Parameter(typeof(object), "propertyReference");
        var paramValues = Expression.Parameter(typeof(object), "value");

        // Convert parameters to string arrays
        var propAsStringArray = Expression.Convert(paramProp, typeof(string[]));
        var valuesAsStringArray = Expression.Convert(paramValues, typeof(string[]));

        // Start with a false expression
        Expression containsAnyExpression = Expression.Constant(false);

        // Iterate through values to build the Contains expressions
        foreach (var str in values)
        {
            // Expression for prop.Contains(str)
            var containsExpression = Expression.Call(
                typeof(Enumerable),
                nameof(Enumerable.Contains),
                new Type[] { typeof(string) },
                propAsStringArray,
                Expression.Constant(str)
            );

            // Combine with the existing expressions using Expression.OrElse
            containsAnyExpression = Expression.OrElse(containsAnyExpression, containsExpression);
        }

        // Create and return the final lambda expression
        return Expression.Lambda<OperatorParameter>(containsAnyExpression, paramProp, paramValues);
    }
```

**Comment by alirezanet** [comment]
> LINQ queries to EFCore will have exactly the same issues.

This is EntityFramework limitation, and I think it is fixed in [EF8](https://devblogs.microsoft.com/dotnet/announcing-ef8-preview-4/) so honestly I don't think it would be a useful feature in the near future since first, no one is going to use it anymore because [`#In`](https://alirezanet.github.io/Gridify/guide/filtering#custom-operators) operator works as expected even in EntityFramework latest versions and second the syntax is just different and this `fc=Red|fc=Blue` syntax is working as expected.

although, if you want to use Expression to alter the query you have access to the FilteringExpressions in Gridify, but unfortunately most of the classes in the Syntax namespace at this moment are `internal`:

```csharp
var mapper = new GridifyMapper<Artist>().AddMap("fc", q=>q.FavouriteColors.Select(fc=>fc));

// generates the whole syntax tree
var syntaxTree = SyntaxTree.Parse("fc=Blue;Red", null);

// generates the query expression 
var expression = syntaxTree.CreateQuery<Artist>(mapper);
```
--- 

I'll make some internal APIs public in the next version so in these situations you could use them.

**Comment by alirezanet** [comment]
Hi @Kuchasz,
I've just released a new preview version, `2.15.0-preview2`, which supports Mapping Generation and Contains queries for lists of simple types. I'm still testing it but I'd appreciate it if you could also test it out and share your feedback with me. 

so basically you should be able to achieve this query in this version:
```csharp
query.Where(a =>a.FavouriteColors.Contains("Red") 
    || a.FavouriteColors.Contains("Blue") 
    || a.FavouriteColors.Contains("Green") 
    || a.FavouriteColors.Contains("Foo"));
```
although the syntax is still the same, 
```csharp
.ApplyFiltering("fc=Red|fc=Blue|fc=Green|fc=Foo")
```

thank you in advance

**Comment by alirezanet** [comment]
for your information, the internal API was exposed in `2.15.0-preview3`. From this version onwards, you can utilize the `SyntaxTree.Parse` method to manually generate your queries.

**Comment by Kuchasz** [comment]
Thank you very much! I will take a look at this when i'll sit down to improvements to my grid.

**Comment by Kuchasz** [comment]
Hi @alirezanet, 
I had to make some improvements in my internal grid, add Contains filter for enum column. My custom operator just wasn't ready to handle other than string primivites. I bumped grifidy to most recent preview3, removed my #In operator i tried to run the app. I got some exceptions complaining about conversion of string to IEnumerable<strings>. I had to change IEnumerable<string> i used in my database model to List<string> and it started working wel even with those enums. Those internal apis you've exposed recently are not needed for me (at least for now).

What can i do to help you identify and fix such incompatibilities like that IEnumerable.

**Comment by alirezanet** [comment]
Hi @Kuchasz,

If you think there is a valid scenario that is not supported, it would be helpful if you could create an issue and provide an example of how we can simulate the scenario. This will help us identify the problem. I have conducted many tests showing that if you define your mappings correctly, the `FavouriteColors` example works as expected.
