### ISSUE TITLE
Filtering for null/empty case insensitive

### ISSUE THREAD

**Issue by brendonparker** [alirezanet/Gridify#171]
### Version

2.14.1

### Details

**Thanks for this great library! It really is awesome!**

When I attempt to submit a filter like: `name=/i` an exception is thrown:

>Gridify.GridifyFilteringException: 'Unexpected token <CaseInsensitive> at index 7, expected <ValueToken>'

I'm using `gridify-client` on the front-end to construct the filter. 

I can (and have) changed my code around this to prevent this state/combination of CI + Empty. But seems this could be better handled either by the Gridify code or gridify-client code.

IMO the case-insensitive (`/i`) should just be ignored in this scenario, and no exception should be thrown.

### Steps to reproduce

Failing test (throws an exception):
```csharp
[Fact] // issue #??
public void ApplyFiltering_CaseInsensitiveEmptyFields_ShouldFilter()
{
   var actual = _fakeRepository.AsQueryable().ApplyFiltering("name=/i").ToList();
   var expected = _fakeRepository.Where(q => string.IsNullOrEmpty(q.Name)).ToList();

   Assert.Equal(expected.Count, actual.Count);
   Assert.Equal(expected, actual);
   Assert.True(actual.Any());
}
```

**Comment by alirezanet** [comment]
Hello @brendonparker,
Thank you for the positive feedback regarding the library. I'm pleased to know you find it beneficial.
Great catch! I will aim to resolve this issue in the upcoming version.

**Comment by hershi9** [comment]
@alirezanet Thank you for this great library, it's really awesome!
It appears that the use of parentheses, for instance, _?filter=address=*ad/i,(room=*/i|category=*/i)_ throws a  _Gridify.GridifyFilteringException: Unexpected token CaseInsensitive at index 23, expected CloseParenthesis_ error.
Is this a bug or an expected behaviour?

**Comment by alirezanet** [comment]
Hi @hershi9,
I believe this is a bug, would be nice if you could create a separate issue for this.
