### ISSUE TITLE
Compiled Expressions

### ISSUE THREAD

**Issue by cirrusone** [alirezanet/Gridify#18]
I've been using your library against standard collections such as arrays, lists and dictionaries and not databases. It would be really nice to have the ability to compile the filter if possible as it can often improve performance.  [Compile Method](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression-1.compile?view=net-5.0)

For example:

`var query = collection.AsQueryable().ApplyFiltering(Filter: "name = John", Compiled: true);`

and

`var query = new GridifyQuery { Filter = "name = John", Compiled = true };`

**Edit:** Thinking more about this, compiled filters are about both performance and re-use of the filter. It would probably work more like this

`var compiledFilter = CreateFilter(Filter: "name = John", Compiled: true);`

and then reuse it as 
`var query = collection.AsQueryable().ApplyFiltering(compiledFilter);`
`var query = new GridifyQuery { Filter = compiledFilter };`

**Comment by alirezanet** [comment]
Hi, 
The compiled idea is great but I'm not sure having a `compiled` option is the best way to implement this.
for example, if we are working with Enumerables and arrays we don't need to use the `.AsQueryable` extension, I think a better approach to this could be adding support for using Gridify methods directly on collections, this way  Gridify can always compile the queries. 
if the user doesn't want to have a compiled query, he can use the `.AsQueryable` extension to enter the expression word.
what do you think?

**Comment by alirezanet** [comment]
Also, I forget to mention that, you can get the compiled expression in all recent versions of Gridify.
eg:
```c#
var gm = new GridifyMapper<TestClass>().GenerateMappings();
var gq = new GridifyQuery() {Filter = "name=John"};
var compiledExpression = gq.GetFilteringExpression(gm).Compile();
```

**Comment by cirrusone** [comment]
I think your idea is better, it allows more options depending on usage.

I've just tested `var compiledExpression = gq.GetFilteringExpression(gm).Compile();`, is this a comparable benchmark? It's a decent performance uplift if comparable.

![Untitled](https://user-images.githubusercontent.com/10389314/133829881-8e326d9f-7118-436e-a2c5-b74809064c0a.png)

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic.Core;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Engines;
using BenchmarkDotNet.Order;
using Fop;
using Fop.FopExpression;
using Gridify;
using Gridify.Tests;
using Microsoft.Extensions.Options;
using Sieve.Models;
using Sieve.Services;

namespace Benchmarks
{
   [MemoryDiagnoser]
   [RPlotExporter]
   [Orderer(SummaryOrderPolicy.FastestToSlowest)]
   public class LibraryComparisionFilteringBenchmark
   {
      private static readonly Consumer Consumer = new();
      private TestClass[] _data;
      private IQueryable<TestClass> Ds => _data.AsQueryable();

      private IGridifyMapper<TestClass> gm;
      private GridifyQuery gq;
      Func<TestClass, bool> compiledExpression;

      [GlobalSetup]
      public void Setup()
      {
         _data = GetSampleData().ToArray();

         gm = new GridifyMapper<TestClass>().GenerateMappings();
         gq = new GridifyQuery() { Filter = "Name=*a,Id>5,Name=Ali" };
         compiledExpression = gq.GetFilteringExpression(gm).Compile();
      }

      [Benchmark(Baseline = true)]
      public void NativeLinQ()
      {
         Ds.Where(q => q.Name.Contains("a") && q.Id > 5 && q.Name == "Ali").Consume(Consumer);
      }

      [Benchmark]
      public void Gridify()
      {
         Ds.ApplyFiltering("Name=*a,Id>5,Name=Ali").Consume(Consumer);
      }

      [Benchmark]
      public void GridifyCompiled()
      {
         var x = compiledExpression(Ds.First());
      }

      private static IEnumerable<TestClass> GetSampleData()
      {
         var lst = new List<TestClass>();
         lst.Add(new TestClass(1, "John", null, Guid.NewGuid(), DateTime.Now));
         lst.Add(new TestClass(2, "Bob", null, Guid.NewGuid(), DateTime.UtcNow));
         lst.Add(new TestClass(3, "Jack", (TestClass)lst[0].Clone(), Guid.Empty, DateTime.Now.AddDays(2)));
         lst.Add(new TestClass(4, "Rose", null, Guid.Parse("e2cec5dd-208d-4bb5-a852-50008f8ba366")));
         lst.Add(new TestClass(5, "Ali", null));
         lst.Add(new TestClass(6, "Hamid", (TestClass)lst[0].Clone(), Guid.Parse("de12bae1-93fa-40e4-92d1-2e60f95b468c")));
         lst.Add(new TestClass(7, "Hasan", (TestClass)lst[1].Clone()));
         lst.Add(new TestClass(8, "Farhad", (TestClass)lst[2].Clone(), Guid.Empty));
         lst.Add(new TestClass(9, "Sara", null));
         lst.Add(new TestClass(10, "Jorge", null));
         lst.Add(new TestClass(11, "joe", null));
         lst.Add(new TestClass(12, "jimmy", (TestClass)lst[0].Clone()));
         lst.Add(new TestClass(13, "Nazanin", null));
         lst.Add(new TestClass(14, "Reza", null));
         lst.Add(new TestClass(15, "Korosh", (TestClass)lst[0].Clone()));
         lst.Add(new TestClass(16, "Kamran", (TestClass)lst[1].Clone()));
         lst.Add(new TestClass(17, "Saeid", (TestClass)lst[2].Clone()));
         lst.Add(new TestClass(18, "jessi==ca", null));
         lst.Add(new TestClass(19, "Ped=ram", null));
         lst.Add(new TestClass(20, "Peyman!", null));
         lst.Add(new TestClass(21, "Fereshte", null));
         lst.Add(new TestClass(22, "LIAM", null));
         lst.Add(new TestClass(22, @"\Liam", null));
         lst.Add(new TestClass(23, "LI | AM", null));
         lst.Add(new TestClass(24, "(LI,AM)", null));
         return lst;
      }
   }
}
```

**Comment by alirezanet** [comment]
> I've just tested `var compiledExpression = gq.GetFilteringExpression(gm).Compile();`, is this a comparable benchmark? It's a decent performance uplift if comparable.

No, it is true if you use a compiled query you get massive improvements but your benchmark is **not fair** because you ignored the actual compile time.  that's why I didn't include this in my benchmarks.

**Comment by cirrusone** [comment]
The performance of GridifyCompiled is excellent. I know others can also be compile but with additional functionality of Gridify this library is really powerful. Personally, I think this performance is enough so happy if you close this comment.

Thank you for this excellent library.
