### ISSUE TITLE
Case in-sensitive filtering for List<string> does not work

### ISSUE THREAD

**Issue by moxplod** [alirezanet/Gridify#193]
### Version

2.14.2

### Details

I am doing filtering on List<string> primitive type on postgres. 
It works case-sensitive.

However, the case-insensitive filtering does not work.

### Steps to reproduce

From the example -
https://github.com/alirezanet/Gridify/issues/167#issuecomment-2184084975 

`.ApplyFiltering("FavouriteColors=blue/i")`

Does not work.

**Comment by alirezanet** [comment]
Hi @moxplod,

Could you please test this in the latest preview versions as well? Since this feature has changed a lot recently, the issue might be resolved. If not, I'll look into it in a few days.

**Comment by moxplod** [comment]
I just forked the repository and created a test to try it there. Verified that it's not working there.

```c#

   [Fact]
   public void ApplyFiltering_WithoutMapper_ShouldGenerateMappingsForListOfStrings_CaseInsensitive()
   {
      // arrange
      var dataSource = new List<Test>()
      {
         new() {FavouriteColorList = ["Green", "Blue"]},
         new() {FavouriteColorList = ["White", "Yellow"]},
      }.AsQueryable();

      var mapper = new GridifyMapper<Test>()
         .AddMap("FavouriteColorList", w => w.FavouriteColorList.Select(Param_0 => Param_0));
      var expected = dataSource.ApplyFiltering("FavouriteColorList=red/i|FavouriteColorList=blue/i", mapper);

      // act
      var actual = dataSource.ApplyFiltering("FavouriteColorList=red/i|FavouriteColorList=blue/i");

      // assert
      Assert.Equal(expected.ToString(), actual.ToString());
      var actualList = actual.ToList();
      Assert.Equal(expected.ToList(), actualList);
      Assert.Single(actualList);
   }

```

**Comment by moxplod** [comment]
This needs to be reopened.
