### ISSUE TITLE
New case sensitive on preview does not work with EF

### ISSUE THREAD

**Issue by moxplod** [alirezanet/Gridify#203]
### Version

2.15.0-preview6

### Details

I pulled the preview version into my solution and ran my tests. The new case insensitive linq statements do not work with entity framework.

Related changes: https://github.com/alirezanet/Gridify/pull/194

I have these global configurations in my project - 

        GridifyGlobalConfiguration.EnableEntityFrameworkCompatibilityLayer();
        GridifyGlobalConfiguration.CaseInsensitiveFiltering = true;
        GridifyGlobalConfiguration.DefaultDateTimeKind = DateTimeKind.Utc;

Here is an example error - 

> System.InvalidOperationException
The LINQ expression 'DbSet<TestEntity>()
    .Where(t => t.AccountId == __ef_filter__accountId_0)
    .Where(t => t.Name.Contains(
        value: __Value_0, 
        comparisonType: InvariantCultureIgnoreCase))' could not be translated. Additional information: Translation of method 'string.Contains' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
        
        
Another - 

> The LINQ expression 'DbSet<TestEntity>()
    .Where(t => t.AccountId == __ef_filter__accountId_0)
    .Where(t => string.Equals(
        a: t.Name, 
        b: __Value_0, 
        comparisonType: InvariantCultureIgnoreCase))' could not be translated. Additional information: Translation of the 'string.Equals' overload with a 'StringComparison' parameter is not supported. 

        
        

### Steps to reproduce

Provided above.

**Comment by moxplod** [comment]
I read more about this and looks like String.Equals(String, StringComparison) is not supported in ef core. For any SQL databases, SQL server or PostgreSQL. Here is a detailed discussion.

**Comment by moxplod** [comment]
@alirezanet  FYI - https://github.com/dotnet/efcore/issues/1222

**Comment by alirezanet** [comment]
Hi @moxplod,
I didn't expect this 🙁, so I think for now the best solution is reverting our PR #194 and keeping the old code with `ToLower()` method.

**Comment by moxplod** [comment]
Yea - I think that is the best way forward. I have it working locally (with a DLL for now) with the code changes that I had done. From that PR - just keep my commits as they are with the use of the new configuration and ToLower () methods. 

Sorry about this, I also when I read the PR didn't associate that String.Equal with StringComparison is not translatable by EF. We should probably have some integration test that help us with this in the library for the future.

**Comment by moxplod** [comment]
@alirezanet I had some time - did the git revert of the changes. Do take a look - https://github.com/alirezanet/Gridify/pull/205
