### ISSUE TITLE
List<string> or any primitive collection != which translates to Linq Not Contains should check for null as well

### ISSUE THREAD

**Issue by moxplod** [alirezanet/Gridify#204]
### Version

2.14.2

### Details

In the below class. "Tags!=Red" filter will not match any rows that are null. As it is translating in Linq to 

`e => !e.Tags.Contains(tag)`

It should translate to 

`e => e.Tags == null || !e.Tags.Contains(tag)`

```c#

public class TestEntity
{    
    public string Name { get; set; }	
    public List<string> Tags { get; set; }
}

``` 

### Steps to reproduce

Use the filter != on a List<> primitive collection does not match null rows.

**Comment by moxplod** [comment]
@alirezanet  FYI - I have a fix ready for this. But the PR is built on top of the revert of the case-insensitive changes. Once that is merged, I can create a PR for this.

**Comment by alirezanet** [comment]
Hi @moxplod,
can we close this? If I'm not wrong it should be fixed
