### ISSUE TITLE
Relative dates

### ISSUE THREAD

**Issue by moxplod** [alirezanet/Gridify#211]
### Details

In filtering, a very commonly requested feature is to create a filter that has relative dates. 
For example, return all records created "today," "this month" "this year," etc. 

I have implemented this previously. We could implement parsing using Chronic as mentioned in the next comment. Which will translate string to the appropriate datetime.

I can build this outside of Gridify, wanted to hear thoughts on whether this would make sense for the library. 

This will allow us to support filtering like 

"date > 3 days ago"
"date > last week"

As well as doing what we currently support in Gridify 
"date > 8/8/2024"

**Comment by moxplod** [comment]
On more research this is the most popular natural language date/time parser written in pure Ruby https://github.com/mojombo/chronic 

It's dotnet port would make a good way to do this: https://github.com/robbell/nChronic.Core

**Comment by moxplod** [comment]
@alirezanet Would it be ok to depend on that library? What are your thoughts on this feature?

**Comment by moxplod** [comment]
If the code and dependency looks good I will go ahead and add the appropriate documentation.

**Comment by alirezanet** [comment]
Hi @moxplod,
First of all, thank you for the idea. However, this is not something that Gridify should support. We don't want to have any external dependencies, and if anyone is interested in this feature, they can add the `Chronic.Core` library to their project directly. Additionally, for performance reasons, having features that don't align with the query language is not ideal.

**Comment by moxplod** [comment]
Hey @alirezanet that makes sense and I respect the thought to keep external dependencies out of this library. And it's good to understand the priorities here. I will close this draft PR. 

I will move this into custom value convertor in my project. I may still need to submit another PR as I noticed that custom value convertors get overwritten and do not work correctly right now in the BaseQueryBuilder.

**Comment by moxplod** [comment]
Closing this issue as not planned.
