### ISSUE TITLE
Cannot implicitly convert type 'Gridify.Paging<GridifyAdvancedDemo.Product>' to 'System.Linq.IQueryable<GridifyAdvancedDemo.Product>'

### ISSUE THREAD

**Issue by santoshpatro** [alirezanet/Gridify#217]
### Version

2.14.2

### Details

I encountered an issue related to typecasting while using Gridify verion: 2.14.2. I have submitted a question with all the details at : https://stackoverflow.com/questions/78952345/cannot-implicitly-convert-type-gridify-paginggridifyadvanceddemo-product-to

### Steps to reproduce

https://stackoverflow.com/questions/78952345/cannot-implicitly-convert-type-gridify-paginggridifyadvanceddemo-product-to

**Comment by alirezanet** [comment]
Hello @santoshpatro,
I have responded to your StackOverflow question, and I believe the article may contain inaccuracies and could potentially be misleading.
