### ISSUE TITLE
Dictionary filtering against Cosmos fails

### ISSUE THREAD

**Issue by RetroCoder** [alirezanet/Gridify#227]
### Version

2.15.0-preview7

### Details

When I use the following mapping, I get an error.

var gm = new GridifyMapper<AuditLogDetailDto>().AddMap("dictProp", (target, key) => target.Payload[key]);

I am using this with Microsoft.Azure.Cosmos (3.45.0).

The error shown is: Method 'ContainsKey' is not supported., Windows/10.0.22631 cosmos-netstandard-sdk/3.36.1

The query generates the following: 
.Call ($target.Payload).ContainsKey("additionalField3.previousValue") && .Call ($target.Payload).get_Item("additionalField3.previousValue")== "123"

### Steps to reproduce

Attempt to query Cosmos that has a dictionary of properties. Setup Gridify to filter on one of these properties using the GridifyMapper. Query the Cosmos db and you will see the error. I am using the 'FeedIterator' with the generated IQueryable.

**Comment by alirezanet** [comment]
Hi @RetroCoder,
Please also share how you query data manually without Gridify. I want to understand if they don't support the `ContainsKey` method, what is supported instead for dictionaries in Cosmos DB

**Comment by alirezanet** [comment]
So you don't have any null checks, you can disable the automatic null checks in Gridify:

```csharp
 GridifyGlobalConfiguration.DisableNullChecks = true;     
```

**Comment by RetroCoder** [comment]
Yep, that fix the issue. Thanks for the fast response.
