### ISSUE TITLE
Change the `Page` type to int

### ISSUE THREAD

**Issue by VahidN** [alirezanet/Gridify#23]
The `Page` property in IGridifyPagination [is defined as](https://github.com/alirezanet/Gridify/blob/master/src/Gridify/IGridifyPagination.cs#L5) `short`. It's better to define it as `int` the same as `PageSize` which its value is always less than the `Page`'s value.

**Comment by alirezanet** [comment]
Thank you for the feedback.

**Comment by alirezanet** [comment]
This is available in the version `v2.2.0`.
