### ISSUE TITLE
Using EF 9 in a .NET 8 project

### ISSUE THREAD

**Issue by ValeriyGourov** [alirezanet/Gridify#240]
### Version

2.16.0

### Details

As mentioned in the [documentation](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-9.0/whatsnew):

> EF9 targets .NET 8, and can therefore be used with either .NET 8 (LTS) or .NET 9.

But when I use Entity Framework 9 in a .NET 8 project, I get the [NU1608](https://learn.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1608) warning for "Gridify.EntityFramework":

> Detected package version outside of dependency constraint: Gridify.EntityFramework 2.16.0 requires Microsoft.EntityFrameworkCore (>= 8.0.0 && < 9.0.0) but version Microsoft.EntityFrameworkCore 9.0.0 was resolved.

I think it's because of [`src/Gridify.EntityFramework/Gridify.EntityFramework.csproj`](https://github.com/alirezanet/Gridify/blob/master/src/Gridify.EntityFramework/Gridify.EntityFramework.csproj):

```xml
<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
   <PackageReference Include="Microsoft.EntityFrameworkCore" Version="[8.0.0,9.0.0)" />
</ItemGroup>
```

Is it possible to define the version like `"[8.0.0,10.0.0)"`?

### Steps to reproduce

- Create a .NET 8 project..
- Add "Microsoft.EntityFrameworkCore 9.0.0" package.
- Add "Gridify.EntityFramework 2.16.0" package.
- There is a NU1608 warning in the Error list or in the build messages.

**Comment by alirezanet** [comment]
Hey @ValeriyGourov,

Good catch! You're absolutely right about the version range needing an update. If you’ve already looked into it, feel free to open a PR—would be great to collaborate! Otherwise, I’ll get this sorted soon.

Appreciate the input!

**Comment by ValeriyGourov** [comment]
@alirezanet I've created a PR: https://github.com/alirezanet/Gridify/pull/241.
