### ISSUE TITLE
Comparison operations and string types

### ISSUE THREAD

**Issue by VahidN** [alirezanet/Gridify#27]
Suppose our `AddDate` field is defined as an `string` and its column has values such as `1400/07/06`, etc. If I apply the `>` opertaor to it, the result will be:
```
System.InvalidOperationException: 
The binary operator GreaterThan is not defined for the types 'System.String' and 'System.String'.
```
EF-Core and SQL are able to compare strings using the [string.Compare](https://docs.microsoft.com/en-us/dotnet/api/system.string.compare?view=net-5.0). 
I think this case should use the `string.Compare` method, instead of `>`, `<`, `>=` and `<=` for strings.

**Comment by alirezanet** [comment]
Hi, Thank you for the feedback. 
I fixed this issue, can you confirm is this the behavior you **expected?**
e.g: 

```c#
      [Fact] // issue #27
      public void ApplyFiltering_GreaterThanOrEqualBetweenTwoStrings() 
      {
         var actual = _fakeRepository.AsQueryable().ApplyFiltering("name >= c" ).ToList();
         var expected = _fakeRepository.Where(q => string.Compare(q.Name, "c", StringComparison.Ordinal ) >= 0  ).ToList();
         
         Assert.Equal(expected.Count, actual.Count);
         Assert.Equal(expected, actual);
         Assert.True(actual.Any());
      }
```
[other tests.](https://github.com/alirezanet/Gridify/blob/17988c9acd0e15fef5a1274b40e4bd970deab0f2/test/Gridify.Tests/GridifyExtensionsShould.cs#L450)

If you confirm it will be released in the next minor version. thank you.

**Comment by VahidN** [comment]
Thanks. EF-Core doesn't like the **third parameter** here!
It translates
```C#
var res = query.Where(q => string.Compare(q.Name, "c") >= 0).ToList();
```
To:
```sql
 SELECT [g].[Id], [g].[Name]
      FROM [Genres] AS [g]
      WHERE [g].[Name] >= N'c'
```
But it can't translate the query when `StringComparison.xyz` is specified:
```C#
var res = query.Where(q => string.Compare(q.Name, "c", StringComparison.Ordinal) >= 0).ToList();
```
Result:
```
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: The LINQ expression 'DbSet<Genre>()
          .Where(g => string.Compare(
              strA: g.Name,
              strB: "c",
              comparisonType: Ordinal) >= 0)' could not be translated.
```

**Comment by alirezanet** [comment]
The translating to SQL query part is the problem. by default, we should always use the third parameter according to [Microsoft documentation](https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings) because Gridify is not limited to EntityFramework, but for compatibility, I'll probably add a global configuration `EntityFrameworkCompatibilityLayer` in the `Gridify.EntityFramework` to make underlying functions compatible to EntityFramework.

**Comment by alirezanet** [comment]
This feature is available in version `v2.2.0`. 
if you want to use this feature in SqlServer and MySql providers alongside with EntitiyFramework you should enable the compatibility layer from the `Gridify.EntityFramework` package.

e.g 
```c#
  // You should use this configuration in your startup class or main method.
  GridifyGlobalConfiguration.EnableEntityFrameworkCompatibilityLayer();
```

**Comment by VahidN** [comment]
Thanks. Make [this property](https://github.com/alirezanet/Gridify/blob/master/src/Gridify/GridifyExtensions.cs#L13) public. Maybe someone just wants to use the original package.

**Comment by alirezanet** [comment]
> Thanks. Make [this property](https://github.com/alirezanet/Gridify/blob/master/src/Gridify/GridifyExtensions.cs#L13) public. Maybe someone just wants to use the original package.

You're welcome., thank you for the feedback. 
I really thought about this, there is nothing related to EntityFramework in the Gridify package, if I make this property public we really don't need the GridifyGlobalConfiguration class. I chose the harder way to keep the SoC. Also, if the user using gridify alongside EF they should install the `Gridify.EntityFramework` package only. but  To be honest I'm not really sure this is a good solution or not yet. what is your opinion? having EntityFramework related configuration in the gridify package don't violate SoC?

**Comment by VahidN** [comment]
Or you can just simply add it here:
```C#
var gQuery = new GridifyQuery()
{
    // ...

    IsEntityFrameworkCompatibe = true  
};

```

**Comment by alirezanet** [comment]
> Thanks. Make [this property](https://github.com/alirezanet/Gridify/blob/master/src/Gridify/GridifyExtensions.cs#L13) public. Maybe someone just wants to use the original package.

Hi,
It is public now, check out the docs [Here](https://alirezanet.github.io/Gridify/guide/gridifyGlobalConfiguration.html#entityframeworkcompatibilitylayer)

Thanks for the feedback
