### ISSUE TITLE
Support EF.Functions.FreeText

### ISSUE THREAD

**Issue by sebdm** [alirezanet/Gridify#42]
I'd like free text searches to (optionally) be able to use EF.Functions.FreeText rather than a LIKE with wildcards. This would greatly improve the performance of free text searches with wildcards on both sides of the search string.

**Comment by alirezanet** [comment]
Hi, 

To add this feature first we need to answer a few questions. 

1. How we can _optionally_ switch between FreeText and the normal Contains method (Like)?
2. Should we drop Dotnet Framework EF6 support? 
3. Because gridify is not limited to a specific database, do all EF core providers support this function?
4. How much do we gain a performance boost, is that worth the effort?

I'll do a research about this later, feel free to answer these questions if you already have the answers.

Thank you for the feedback

**Comment by Nokecy** [comment]
support EF.Property<string> like  `x=> EF.Property<string>(x,\"Name\") == \"Ford\"`

**Comment by Nokecy** [comment]
is it possible ? @alirezanet 

> support EF.Property like `x=> EF.Property<string>(x,\"Name\") == \"Ford\"`

**Comment by alirezanet** [comment]
> is it possible ? @alirezanet
 
Yes, kind of...
This idea to support EF functions can solve a lot of problems, but implementing this is not so simple, because it can cause breaking changes in other gridify features. (the main problem is replacing gridify operators with ef function)

I will check it out later to see what I can do,

**Comment by alirezanet** [comment]
Hi, 
Check out `v2.6.0` and the new  [`CustomOperator` feature](https://alirezanet.github.io/Gridify/guide/gridifyGlobalConfiguration.html#customoperators). 

``` c#
   [Fact]
   public void ApplyFiltering_EFFunction_FreeTextOperator()
   {
      GridifyGlobalConfiguration.CustomOperators.Register(new FreeTextOperator());

      // Arrange
      var expected = _dbContext.Users.Where(q => EF.Functions.FreeText(q.Name, "test")).ToQueryString();

      // Act
      var actual = _dbContext.Users.ApplyFiltering("name #= test").ToQueryString();

      // Assert
      Assert.Equal(expected, actual);
   }

   internal class FreeTextOperator : IGridifyOperator
   {
      public string GetOperator() => "#=";

      public Expression<OperatorParameter> OperatorHandler()
      {
         return (prop, value) => EF.Functions.FreeText(prop, value.ToString());
      }
   }
```

**Comment by Nokecy** [comment]
cool ~~

**Comment by riccardorestagno** [comment]
I really like this feature! It adds a lot of flexibility

**Comment by Nokecy** [comment]
What should I do if I want to support EfCore's shadow property? like `x=> EF.Property<string>(x,\"Name\") == \"Ford\"` @alirezanet

**Comment by alirezanet** [comment]
Hi @Nokecy 
I think having an operator for shadow properties doesn't make sense, It should be supported via GridifyMapper. Open a new issue I'll look into this.

**Comment by Nokecy** [comment]
use `var mapper = new GridifyMapper<User>(true).AddMap("shadow1", q => EF.Property<string>((User)q, "shadow1"),v=>v);` is work
