### ISSUE TITLE
Filtering on Datetimes

### ISSUE THREAD

**Issue by staelenslennert** [alirezanet/Gridify#49]
I'm unable to make it work to filter on Datetimes, any help?

**Comment by alirezanet** [comment]
Hello,
what is the problem?
```c#
void Main()
{
	// test data
	var data = new List<TestClass>
	{
		new TestClass(DateTime.Parse("2022/01/01")),
		new TestClass(DateTime.Parse("2022/02/01")),
		new TestClass(DateTime.Parse("2022/03/01")),
		new TestClass(DateTime.Parse("2022/04/01")),
	};

	// eg1. using extensions
	var result2 = data.AsQueryable().ApplyFiltering("date<2022/04/01");


	// eg2. using query builder
	var result1 = new QueryBuilder<TestClass>()
				.AddCondition("date=2022/01/01")
				.Build(data);
	
	
	result1.Dump();
	result2.Dump();
}

class TestClass
{
	public TestClass(DateTime date)
	{
		Date = date;
	}
	public DateTime Date { get; set; }
}
```

**Comment by staelenslennert** [comment]
So I want to filter on CreationDate.

This is my query, that I send to my api (below):
{
	"pageSize": 10,
	"page": 1,
	"orderBy": "creationDate desc",
	"filter": "creationDate=2021/09/20"
}

If I send my filter like this "filter": "creationDate>2021/09/20" then I get data back, but with the equal operator I'm not getting anything back. Even tough I got a CreationDate that is equal to 2021/09/20 in my database.

public async Task<ServiceResponse<List<ProjectListDto>>> GetProjectsAsync(GridifyQuery gQuery, CancellationToken token)
        {

            var serviceResponse = new ServiceResponse<List<ProjectListDto>>();

            var (count, query) = await Context.Project
                .Include(o => o.Customer)
                .Include(o => o.ProjectItems)
                .Include(o => o.ProjectStatus)
                .Include(o => o.ProjectMissions)
                    .ThenInclude(i => i.AssignedUsers)
                .GridifyQueryableAsync(gQuery, new GridifyMapper<Project>().GenerateMappings()
                    .AddMap("projectStatusIsOpen", q => q.ProjectStatus.IsClosed)
                    .AddMap("projectStatus", q => q.ProjectStatus.Name)
                    .AddMap("customer", q => q.Customer.Name)
                    .AddMap("creationDate", q => q.CreationDate)
                    , token);

            var projects = Mapper.Map<List<ProjectListDto>>(query);

            if (!projects.Any())
            {
                serviceResponse.Success = false;
                serviceResponse.Data = new List<ProjectListDto>();
                serviceResponse.Message = "NoProjectsFound.Error";
                return serviceResponse;
            }

            serviceResponse.TotalRecords = count;
            serviceResponse.Success = true;
            serviceResponse.Data = projects;

            return serviceResponse;
        }

**Comment by alirezanet** [comment]
>This is my query, that I send to my api (below):
> {
> "pageSize": 10,
> "page": 1,
> "orderBy": "creationDate desc",
> "filter": "creationDate=2021/09/20"
> }
> 
> If I send my filter like this "filter": "creationDate>2021/09/20" then I get data back, but with the equal operator I'm not getting anything back.

There are two possible reasons: 

1. DateTime in Dotnet comes with extra time data for example `2021/09/20 06:31:36` so two dates are not equal always. Try using `.Date` in your mappings to exclude the time part if you want to only compare the dates.  ` .AddMap("creationDate", q => q.CreationDate.Date)`

2. If you create your query on the client-side don't forget to encode the query strings. to make sure this is not related to encodings try to debug your application and double-check the `gQuery` Filter property.

**Comment by staelenslennert** [comment]
So I changed my mapping to exclude the time part and it works. Silly of me that I didn't think of that myself. Thanks for helping!
