### ISSUE TITLE
Error with GridifyQueryable

### ISSUE THREAD

**Issue by vklymchuk** [Alirezanet/Gridify#5]
Hi. Thanks for the great library.
I get an error after applying GridifyQueryable to my query. This error raises only when I change sortBy to some columns. For example my string columns in sortBy works as expected but when I pass Id(int) or StartDate(DateTime) I get:

`..
could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). `

Example of filter model:
```
{
    Filter = null,
    IsSortAsc = true,
    Page = 1,
    PageSize = 25,
    SortBy = "startDate"
};
```

**Comment by Alirezanet** [comment]
Hello @vklymchuk, Looks like this is an Entity framework exception. In EF 3.x or up you have some limitations in server-side queries that you need to do on the client-side.  

Please add an `OrderBy( q => q.StartDate )` on your query  and remove `SortBy = ""`  to make sure this is a Gridify issue or EF one.

**Comment by vklymchuk** [comment]
With sortBy = null in the model and     
```
      var filteredQuery = query.GridifyQueryable(filter);
      var data = filteredQuery.Query.OrderBy(q => q.StartDate).ToList();
```
it works.

**Comment by Alirezanet** [comment]
Ok, looks like we have a parsing problem here.
what is the string you pass to the `SortBy`?

**Comment by vklymchuk** [comment]
![image](https://user-images.githubusercontent.com/68416729/123435112-dbf5c700-d5d5-11eb-8c7a-890a20b205fe.png)

//*-----------------------------------------------------------------------------------------------------------------*//

![image](https://user-images.githubusercontent.com/68416729/123435288-17909100-d5d6-11eb-9ac1-c8ef40030f79.png)

**Comment by Alirezanet** [comment]
I am investigating the problem but I have not been able to simulate it yet, 
```CSharp
      [Fact]
      public void ApplyOrdering_SortBy_DateTime()
      {
         var gq = new GridifyQuery {SortBy = "MyDateTime", IsSortAsc = true};
         var actual = _fakeRepository.AsQueryable()
            .ApplyOrdering(gq)
            .ToList();
         var expected = _fakeRepository.OrderBy(q => q.MyDateTime).ToList();

         Assert.Equal(expected, actual);
         Assert.Equal(expected.First().Id, actual.First().Id);
      }

```
what version of EntityFramework are you using?

**Comment by vklymchuk** [comment]
Microsoft.EntityFrameworkCore 3.1.0

**Comment by vklymchuk** [comment]
The same situation is in another service with different query. Both have inner joins and some left joins. Both make a new projection of all the tables to a ViewModel.

**Comment by Alirezanet** [comment]
All Gridify is doing is simply replacing your text representation with an expression,  so normally if Gridify generated expression can't be translated by EFCore, normal calls like `.OrderBy` must have the same problem. the weird part, in this case, is your manual OrderBy is working! 
can you provide a small sample of your situation? I need to somehow reproduce the problem to find out what is wrong

**Comment by vklymchuk** [comment]
I'll try to make a repro project.

**Comment by vklymchuk** [comment]
I successfully reproduced bug in my cleared solution. And after that I decided to update EntityFrameworkCore to a newer bugs patch version. Of course it works )).
So it's my fault and that thing I had to do first.
Thanks for your support.
