### ISSUE TITLE
Filtering with Null values

### ISSUE THREAD

**Issue by vklymchuk** [Alirezanet/Gridify#6]
Hi again!

I have some troubles with filtering.

When I apply 
` "filter": "ResId==1|ResId==2"
...`

I get
```
System.ArgumentException: An item with the same key has already been added. Key: Param_0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.EntityFrameworkCore.Query.ExpressionEqualityComparer.ExpressionComparer.CompareLambda(LambdaExpression a, LambdaExpression b)
```
I don't understand why, but this behavior exists only with 1|2 values. 1|3, 1|4.. works and even 2|1 filter works.

And how can I specify NULLable field?
` "filter": "ResId==1|ResId==null"
...`

I get
```
System.ArgumentNullException: Value cannot be null. (Parameter 'expression')
   at System.Dynamic.Utils.ContractUtils.RequiresNotNull(Object value, String paramName, Int32 index)
```
but ResId has int? type.

**Comment by Alirezanet** [comment]
Hello
you first problem is not clear yet because you can use a field-name multiple times. so you need to provide more information.

but about your second question about null:
by default gridify does not have any `magic string` to handle null strings yet but you can define it if you need.
you need to create a custom mapping (GridifyMapper) and implement your own null handling. 
e.g look at this test:
```csharp
      [Fact]
      public void ApplyFiltering_NullQuery()
      {
         // create custom mapper
         var gm = new GridifyMapper<TestClass>().GenerateMappings();

         // map any string to related property , also use Client convertor to handle custom scenarios
         gm.AddMap("date", g => g.MyDateTime, q => q == "null" ? null : q);

         var gq = new GridifyQuery {Filter = "date==null"};

         var actual = _fakeRepository.AsQueryable()
            .ApplyFiltering(gq, gm)
            .ToList();

         var expected = _fakeRepository.Where(q => q.MyDateTime == null).ToList();
         Assert.Equal(expected.Count, actual.Count);
         Assert.Equal(expected, actual);
         Assert.True(actual.Any());
      }
```

**Comment by vklymchuk** [comment]
> you need to create a custom mapping (GridifyMapper) and implement your own null handling.
Thanks, implemented.

> you need to provide more information to help reproduce the problem.
Try to repeat filtering with the same filter query please. I noticed it'd occured when I send one request to api twice or more.

**Comment by Alirezanet** [comment]
your welcome.
I think your problem is not related to Gridify because internally Gridify is not using any Dictionary at all. 
look at the second line of your error message:
```
System.ArgumentException: An item with the same key has already been added. Key: Param_0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
```
it can not add some Keys to some dictionary... I'm 90 percent sure it is not a Gridify exception.
but try to create a small repo to reproduce the problem, I can't find any errors in my tests.

**Comment by vklymchuk** [comment]
Here is a simple solution. In the console app I execute one method from RecipientService twice. Please specify your connection string or change to what you need in OMS.Entity -> Context -> OMSContext file and update a db with Initial migration.
[OMSsimple.zip](https://github.com/Alirezanet/Gridify/files/6739150/OMSsimple.zip)

**Comment by Alirezanet** [comment]
this error is related to Entity Framework Service Provider Caching system. I will investigate more on this to find out why this is happening and what is the best way to handle similar cases. mean while you can disable service provider caching.
```csharp
      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            //optionsBuilder.UseInMemoryDatabase("mydb");
            optionsBuilder.EnableServiceProviderCaching(false);
        }
```

**Comment by Alirezanet** [comment]
@vklymchuk 
I've added EntityFramework ServiceProviderCaching support to Gridify. you can use this feature in the next release.
good luck and thanks you.
