### ISSUE TITLE
Nested Collections filtering with NHibernate and .NET 5.0

### ISSUE THREAD

**Issue by Leonardofc12** [alirezanet/Gridify#70]
### Version

2.7.0

### Details

Hi,

I'm having problems Nested Collections filtering

The Data Schema is as follows (User - UserProfiles - Profile). A user can contain a list of UserProfile (Associative class between users and profile).
Gridify Mapping
`.AddMap("ProfileName", u => u.Profiles.Select(p => p.Profile.Name));`

When I try to filter a user by some profile name, the following script is injected into the query using NHibernate and .NET 5.0
`and ( . is not null)`

Debugging gridify, I found the **GetExpressionWithNullCheck** method that adds this check to the expression.
Result of GetExpressionWithNullCheck
`{u => ((u.UserProfiles != null) AndAlso u.UserProfiles.Any(p => (p.Profile.Name== value(GridifyDisplayClass).Value )))}`

The `(u.UserProfiles != null)` condition, in NHibernate doesn't work very well.  Breaking the query with `and ( . is not null)`

I found that a similar change has already been made in the .NET Framework (issue #58) and I would like to know if it is possible to adjust it in .NET5.0 using NHibernate.

If it returns `Expression.Lambda(right, param);` in the GetExpressionWithNullCheck method, Filtering works.

### Steps to reproduce

Gridify Mapping
`.AddMap("ProfileName", u => u.Profiles.Select(p => p.Profile.Name));`

**Comment by alirezanet** [comment]
Hi, this can be also a problem in other ORMs too, so I decided to add a global configuration to give control to the end-user. 
Unfortunately, I don't have the testing infrastructure for NHibernate at the moment. can you please check `v2.7.1` and the new global configuration ([DisableNullChecks](https://alirezanet.github.io/Gridify/guide/gridifyGlobalConfiguration.html#disablenullchecks)) to confirm it solves the problem or not? 
thanks

**Comment by Leonardofc12** [comment]
I just tested the change, and it worked!!!
Thank you!
