### ISSUE TITLE
 Support parsing 0 & 1 for Boolean values

### ISSUE THREAD

**Issue by reisi-h** [alirezanet/Gridify#71]
### Version

2.7

### Details

If we apply filtering on boolean fields (columns) the where expression  produces wrong statement.
for example if my model has a boolean field named IsImport and create filter "IsImport =1" and apply GridifyQueryable on it we get this result as where statement : 
In DebugView.Expression : 
...
.Where(namelessParameter{0} => False)
...

In DebugView.Query : 
...
WHERE 0 = 1
...

### Steps to reproduce

apply filter on boolean fields

**Comment by alirezanet** [comment]
Hi, 
Currently, boolean values are only parsable using `true` and `false` keywords. but you're right it should be better if we support numbers too.

``` csharp
var qb = new QueryBuilder<User>()
	.AddCondition("IsAdult=true")
	.BuildFilteringExpression()
	.ToString()
	.Dump();

// output => Param_0 => (Param_0.IsAdult == True)
	
public class User
{
	public int Id {get; set;}
	public string Name { get; set; }
	public bool IsAdult { get; set;}
}
```

**Comment by reisi-h** [comment]
thanks for your help. I use true and false instead of 1 and 0 as you suggest

**Comment by alirezanet** [comment]
Hi,
This feature has been added to `v2.7.4`.
