### ISSUE TITLE
Typo in name of nuget package

### ISSUE THREAD

**Issue by ashkanRmk** [alirezanet/Gridify#74]
### Version

2.7.1

### Details

the name of package in nuget is:
```Gridify.EnitityFramework```
instead of:
```Gridify.EntityFramework```

### Steps to reproduce

install nuget package

**Comment by alirezanet** [comment]
Hi, @ashkanRmk 
I think you were referring to the docs and you were right. 
but the actual package name is correct.
I updated the documentation. 
thanks
