### ISSUE TITLE
ts js mappings for group filtering

### ISSUE THREAD

**Issue by Diaskhan** [alirezanet/Gridify#78]
### Details

Hie peoople.

I have few questions about typescript and js.

1.Is there some ts js helpers like this
https://github.com/nestjsx/crud/wiki/Requests#frontend-usage ?

It could help make type specific filters on Frontend.
https://primefaces.org/primeng/table/filter

![image](https://user-images.githubusercontent.com/15046677/164330009-348054a9-c114-4466-8bce-6f402e7f673a.png)

**Comment by alirezanet** [comment]
duplicate #77.
