### ISSUE TITLE
linq to entites suport problem

### ISSUE THREAD

**Issue by masoodinfo** [alirezanet/Gridify#8]
hi alireza 
tnx for library
when i use library like ur example i get this error : Unable to cast the type 'System.String' to type 'System.Object'. LINQ to Entities only supports casting Entity Data Model primitive types

my project on framework 4.6.1 and ef6 edxm file
tnx

**Comment by masoodinfo** [comment]
![1](https://user-images.githubusercontent.com/10396734/128590449-4e9ee6b7-c447-4e0e-b33f-255b204cf106.png)
hi tnx for replay
tajhizreq table has tahvil field

**Comment by alirezanet** [comment]
I've added ef6 ordering support, it will available in the next version. 1.4.2 probably
