### ISSUE TITLE
multiple null or empty filter not working 

### ISSUE THREAD

**Issue by lixlox** [alirezanet/Gridify#85]
### Version

2.8.0

### Details

I have a table for which i wanted to do filtering for multiple fields, filtering for null and string.empty values. I tried it but it failed with an error "`Gridify.GridifyFilteringException: Unexpected token <ValueToken>, expected <End>`". 
Filtering for null and string.empty values works for a unique field that is in the end of the query.

### Steps to reproduce

Filtering with :

((name=),(age=))

or with :

((name=),(age=10))

or with:

( (name=Ali), ( (age=), (id=2) ) )

does'nt work

**Comment by alirezanet** [comment]
Hi @lixlox,
Thank you for the feedback.
Please try version `v2.8.1` problem must have been resolved.
