### ISSUE TITLE
apply multiple sort 

### ISSUE THREAD

**Issue by masoodinfo** [alirezanet/Gridify#9]
hi MR Alireza
i want apply multiple sort on query
 
order by A asc , B desc

i test with below  pseudo code but  just apply  last item
for( var  o in orderlist)
{
  query=quer.applyordering( new gridifyquery( ) { sortby = o.fieldname ,issortasc = o.isasc } )
}

**Comment by masoodinfo** [comment]
If possible, change it as follows
sortby= " A asc, B desc "
and remove issortasc property

**Comment by alirezanet** [comment]
For now, Gridify only supports a single Sort field per gridifyQuery object. maybe in the next versions, I add this feature.
