### ISSUE TITLE
Grammar mistake

### ISSUE THREAD

**Issue by alfadelta88** [alirezanet/Gridify#92]
### Version

2.8.1

### Details

A little grammar mistake in the documentation **QueryablePaging instead of QuaryablePaging**
**[https://github.com/alirezanet/Gridify/blob/master/docs/guide/extensions.md#gridifyqueryable](https://github.com/alirezanet/Gridify/blob/master/docs/guide/extensions.md#gridifyqueryable)**

> Like [ApplyFilteringOrderingPaging](https://alirezanet.github.io/Gridify/guide/extensions.html#ApplyFilteringOrderingPaging) but it returns a `QuaryablePaging<T>`

Should be:
> Like [ApplyFilteringOrderingPaging](https://alirezanet.github.io/Gridify/guide/extensions.html#ApplyFilteringOrderingPaging) but it returns a `QueryablePaging<T>`

### Steps to reproduce

Documentation.

**Comment by alirezanet** [comment]
Hi @alfadelta88, fixed thank you.
