### ISSUE TITLE
Limit page size

### ISSUE THREAD

**Issue by dev-sajad** [alirezanet/Gridify#94]
### Details

Hello Alireza.

I was wondering is there any way to limit page size? for example page size can't be more than 2000 records. for performance and security reasons.

**Comment by dev-sajad** [comment]
For anyone who had same problem. I implemented pagination my self and used this wonderful package for sorting and filtering using ApplyFilteringAndOrdering() method.

**Comment by alirezanet** [comment]
Hi @dev-sajad,

We don't have any limitation for the PageSize, although by default if you don't specify any value it will be set to 20 for performance reasons but you can change it from both client side with passing the desired PageSize or in the backEnd by changing the GlobalConfiguration `GridifyGlobalConfiguration.DefaultPageSize = 500000`
