### ISSUE TITLE
AutoMapper not working

### ISSUE THREAD

**Issue by sangheraajit** [alirezanet/Gridify#98]
### Version

Gridify.EntityFramework 2.83

### Details

We are unable to use ProjectTo
Please find the screen shot for your refeance.

![image](https://user-images.githubusercontent.com/12188266/227183630-f578fa41-6e6e-4e4e-9f85-c085096b3ccc.png)
screenshotreference

### Steps to reproduce

Add package and 
and try to use auto mapper with GridifyQueryable
you will see the attached error

**Comment by alirezanet** [comment]
Hi @sangheraajit,

AutoMapper needs the ConfigurationProvider in order to work, also I suggest to check the [documentation](https://alirezanet.github.io/Gridify/guide/autoMapper.html#gridifyto), and add `GridifyTo` extension method.
